data_root: "./data/nih"
output_dir: "./out/eval/trtr_tstr"



img_size: 512
seed: 42
num_seeds: 1
test_ratio: 0.2
val_ratio: 0.05         

max_per_label_train:
  No Finding: 15000
  Others: 20000
balance_beta: 0.5

batch_size: 16
num_workers: 2
epochs: 15
lr: 0.0001
use_amp: true           
use_data_parallel: true

cache_dir: "./cache512"
